### PR TITLE
The latest PGPSignatureVerifier requires a non-null agent

### PR DESCRIPTION
**Pull request by merks**

### CODE REVIEW

**Comment by merks** [comment]
@mickaelistria @iloveeclipse 

I think this will fix the problem mentioned here;

https://github.com/eclipse-cbi/p2repo-analyzers/pull/16

**Comment by merks** [comment]
I'm not familiar with where the builds are done for that and how they are published...

**Comment by akurtakov** [comment]
I think https://ci.eclipse.org/cbi/job/p2repo-analyzers/job/main/ is it.

**Comment by merks** [comment]
@akurtakov 

Thanks for the link.  I will  put this repository's contents on my radar screen...  

The analyzers are quite slow:

https://ci.eclipse.org/simrel/job/simrel.reporeports.pipeline/

**Comment by iloveeclipse** [comment]
For house keeping: this PR is supposed to fix this https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/740

**Pull request merged**
