### PR TITLE
Another try to fix feature files report.

### PR DESCRIPTION
**Pull request by akurtakov**
https://github.com/eclipse-cbi/p2repo-analyzers/commit/63323346bf9bda77e4eedd10f44a70d7ae4178db has no effect on reports. Thus trying to change in the other very similar place.

### CODE REVIEW

**Comment by akurtakov** [comment]
@merks If this works I propose deleting the class I first edited unless you know a place it is actually used.

**Comment by merks** [comment]
I tried to fix this once too.  😞

**Comment by akurtakov** [comment]
So this one worked. https://download.eclipse.org/eclipse/downloads/drops4/I20230516-1800/buildlogs/reporeports/reports/layoutCheck.txt shows all features being correct. 
@merks Could you please rerun simrel report so we double check this is fixed?

**Comment by merks** [comment]
Here's the new report:

https://download.eclipse.org/staging/2023-06/buildInfo/reporeports/reports/layoutCheck.txt

**Comment by merks** [comment]
I see Oomph has this name for the file  😕 

image

**Comment by akurtakov** [comment]
That should still be accepted but this means Oomph is not using https://github.com/eclipse-cbi/epl-license-feature .

**Comment by merks** [comment]
That's right, Oomph has had its own license feature for a long time.  That's the case for EMF too, but there it has the "right" name:

image

**Comment by akurtakov** [comment]
> Here's the new report:
> 
> https://download.eclipse.org/staging/2023-06/buildInfo/reporeports/reports/layoutCheck.txt

"Only" 62 errors - far better IMHO. Now I'm going to remove the other file.

**Pull request merged**
